apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: localpresistentvolumeclaim
  namespace: busybox
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
  

