apiVersion: v1
kind: PersistentVolume

metadata:
  name: localpersistentvolume
  namespace: busybox
  labels:
    app: localPersistentVolume

spec:
  capacity:
    storage: 1Gi
  accessModes: 
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath: 
    path: /mnt/data
