FROM node:alpine

RUN mkdir -p /usr/src/nodeapp

RUN adduser -D -h /usr/src/nodeapp nodeappuser

RUN chown -R nodeappuser:nodeappuser /usr/src/nodeapp

WORKDIR /usr/src/nodeapp

USER nodeappuser

COPY --chown=nodeappuser:nodeappuser package*.json .

RUN npm install 

COPY --chown=nodeappuser:nodeappuser . .

EXPOSE 3000

CMD [ "npm","start" ]