apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler

metadata:
  name: apachehpa
  namespace: apachenamespace

spec:
  scaleTargetRef:
    kind: Deployment
    name: apachedeployment
    apiVersion: apps/v1

  minReplicas: 1
  maxReplicas: 5

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 5


